# Generated by Django 2.1.4 on 2023-03-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200630_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='client',
            name='title',
        ),
        migrations.AddField(
            model_name='client',
            name='apartment',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='area_name',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='house_no',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
    ]
