# Generated by Django 2.1.4 on 2023-03-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230318_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='town',
        ),
        migrations.AlterField(
            model_name='client',
            name='county',
            field=models.CharField(blank=True, choices=[('Westlands', 'Westlands'), ('Langata', 'Langata'), ('Kibra', 'Kibra'), ('Embakasi North', 'Embakasi North'), ('Embakasi South', 'Embakasi South'), ('Embakasi Central', 'Embakasi Central'), ('Embakasi West', 'Embakasi West'), ('Embakasi East', 'Embakasi East'), ('Makadara', 'Makadara'), ('Starehe', 'Starehe')], default='Kenya', max_length=127, null=True),
        ),
    ]
